name: Deploy a QA por FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Subir cambios por FTP
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repo
        uses: actions/checkout@v4

      - name: Sincronizar por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: /public_html/qaweb.telconnect.cl/wp-content/themes/telconnect/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
